In [4]:
import torch

In [5]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
x.shape

torch.Size([12])

In [7]:
x.numel()

12

In [8]:
X = x.reshape(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [9]:
Y = x.reshape(3, 2, 2)
Y 

tensor([[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]]])

In [10]:
ZeroMar = torch.zeros((2, 3, 4))
ZeroMar

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [11]:
OneMar = torch.ones((2, 3, 4))
OneMar

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [12]:
# 获得均值为 0，标准差为 1 的*高斯*分布（标准正态分布）
torch.randn(2, 3, 4)

tensor([[[-0.0759,  0.3116,  0.8956,  2.4332],
         [ 0.7421, -0.0724, -0.3985, -0.2150],
         [ 1.4925,  0.2012, -0.5484, -0.1344]],

        [[-0.3487, -0.9146,  0.0875,  0.0404],
         [-1.6805,  0.0315,  0.5252,  0.5692],
         [ 0.0319, -0.0483, -0.2753,  0.3020]]])

In [13]:
# 按元素计算
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y, torch.exp(x)

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]),
 tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03]))

In [14]:
# 张量的按维度拼接 concarenate
X = torch.arange(12).reshape(2, 2, 3)
Y = torch.arange(18).reshape(2, 3, 3)
X, Y, torch.cat((X, Y), dim = 1)

(tensor([[[ 0,  1,  2],
          [ 3,  4,  5]],
 
         [[ 6,  7,  8],
          [ 9, 10, 11]]]),
 tensor([[[ 0,  1,  2],
          [ 3,  4,  5],
          [ 6,  7,  8]],
 
         [[ 9, 10, 11],
          [12, 13, 14],
          [15, 16, 17]]]),
 tensor([[[ 0,  1,  2],
          [ 3,  4,  5],
          [ 0,  1,  2],
          [ 3,  4,  5],
          [ 6,  7,  8]],
 
         [[ 6,  7,  8],
          [ 9, 10, 11],
          [ 9, 10, 11],
          [12, 13, 14],
          [15, 16, 17]]]))

In [15]:
X = torch.arange(12).reshape(2, 2, 3)
Y = torch.arange(12).reshape(2, 2, 3)
X == Y

tensor([[[True, True, True],
         [True, True, True]],

        [[True, True, True],
         [True, True, True]]])

In [16]:
X.sum()
# 求和得到张量

tensor(66)

In [18]:
# 广播机制 broadcasting mechanism
# 不同大小的张量运算时，各自扩充适应到合适大小
a = torch.arange(3).reshape(3, 1)
b = torch.arange(2).reshape(1, 2)
a, b, a + b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]),
 tensor([[0, 1],
         [1, 2],
         [2, 3]]))

In [19]:
X[1, 1, 2] = 0
X

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10,  0]]])

In [21]:
X[:, :, 0 : 1] = 0
X

tensor([[[ 0,  1,  2],
         [ 0,  4,  5]],

        [[ 0,  7,  8],
         [ 0, 10,  0]]])

In [25]:
# 节省内存
before = id(X)
X[:] = X + Y
print(id(X) == before)
X += Y
print(id(X) == before)

True
True


In [26]:
import numpy

In [28]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [29]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

总结：
1. 新建一个张量 torch.*
   arange(), zeros(), ones(), randn(), tensor([])
2. 运算
   +, -, *, /, **, ==, torch.exp(), torch.cat((), dim = )
3. 张量属性(假设现在有张量X)
   X.shape, X.numel(), X.sum()
4. 索引访问
   [ : ,  : , ...]
5. 节省内存
   X[:] = ...
   