In [16]:
import torch

In [17]:
scalar = torch.tensor(3.0)
scalar

tensor(3.)

In [18]:
vector = torch.arange(4)
vector

tensor([0, 1, 2, 3])

In [19]:
matrix = torch.arange(20, dtype = torch.float32).reshape(4, 5)
matrix

tensor([[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]])

In [20]:
matrix.T

tensor([[ 0.,  5., 10., 15.],
        [ 1.,  6., 11., 16.],
        [ 2.,  7., 12., 17.],
        [ 3.,  8., 13., 18.],
        [ 4.,  9., 14., 19.]])

In [21]:
n = 2
n * matrix

tensor([[ 0.,  2.,  4.,  6.,  8.],
        [10., 12., 14., 16., 18.],
        [20., 22., 24., 26., 28.],
        [30., 32., 34., 36., 38.]])

In [22]:
# axis 表示要消解的维度
# 进行一次求和时，保持其他维度下标不变，对该维度下下标的所有值对应的数求和
print(matrix.sum())
print(matrix.sum(axis = 0))
print(matrix.sum(axis = 1))
print(matrix.sum(axis = [0, 1]))

tensor(190.)
tensor([30., 34., 38., 42., 46.])
tensor([10., 35., 60., 85.])
tensor(190.)


In [ ]:
# mean 要求 元素为浮点数或复数
matrix.mean(), matrix.sum() / matrix.numel()

(tensor(9.5000), tensor(9.5000))

In [27]:
# 保持轴不变
sum = matrix.sum(axis = 1, keepdim = True)
sum

tensor([[10.],
        [35.],
        [60.],
        [85.]])

In [28]:
matrix / sum

tensor([[0.0000, 0.1000, 0.2000, 0.3000, 0.4000],
        [0.1429, 0.1714, 0.2000, 0.2286, 0.2571],
        [0.1667, 0.1833, 0.2000, 0.2167, 0.2333],
        [0.1765, 0.1882, 0.2000, 0.2118, 0.2235]])

In [30]:
# 累积总和
matrix.cumsum(axis = 1)

tensor([[ 0.,  1.,  3.,  6., 10.],
        [ 5., 11., 18., 26., 35.],
        [10., 21., 33., 46., 60.],
        [15., 31., 48., 66., 85.]])

In [33]:
x = torch.arange(4, dtype = torch.float32)
y = torch.ones(4, dtype = torch.float32)
x, y, torch.dot(x, y), torch.sum(x * y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.), tensor(6.))

In [36]:
matrix, matrix.T.shape, x.shape

(tensor([[ 0.,  1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.,  9.],
         [10., 11., 12., 13., 14.],
         [15., 16., 17., 18., 19.]]),
 torch.Size([5, 4]),
 torch.Size([4]))

In [35]:
torch.mv(matrix.T, x)

tensor([70., 76., 82., 88., 94.])

In [37]:
B = torch.ones(5, 2)
torch.mm(matrix, B)

tensor([[10., 10.],
        [35., 35.],
        [60., 60.],
        [85., 85.]])

In [38]:
# L_2范数 和 L_1 范数
u = torch.tensor([3.0, -4.0])
torch.norm(u), torch.abs(u).sum(), torch.norm(matrix)

(tensor(5.), tensor(7.), tensor(49.6991))